#Make it fancy later. It works, for now.

src_files = [
   'main.cpp',
   'ControlLogic.cpp',
   'fcgiServer/fcgiserver.cpp',
   'base16message.cpp',
   'MessageParser.cpp'
]

env = Environment()

env.Append(CPPFLAGS='-std=c++11')

env.Program(target = 'RobotControlDaemon', source = src_files, LIBS=['fcgi++', 'fcgi', 'pthread', 'cgicc'])

